import "./globals.css";
import { Inter } from "next/font/google";
import Header from "@/src/Header.js";
import Footer from "@/src/Footer";
import Container from "@/src/Container";
import { UserProvider } from "./context/userContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <UserProvider>
      <html lang="pt-br">
        <head>
          <link
            href="https://cdn.jsdelivr.net/npm/simple-datatables@7.1.2/dist/style.min.css"
            rel="stylesheet"
          />
          <link
            rel="stylesheet"
            href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@48,400,0,0"
          />
          <link href="css/styles.css" rel="stylesheet" />
        </head>

        <body className={inter.className}>
          <Header />
          <Container>{children}</Container>
          <Footer />
        </body>
      </html>
    </UserProvider>
  );
}
